### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pokedex.org#2]
A few things that are needed:

1. A URL for each Pokemon, e.g. `pokedex.org/001` for bulbasaur
2. Back/forward events handled correctly
3. All of the above working with refresh
4. All of the above working with ServiceWorker

Due to the complexity of using the actual HTML5 History API and therefore needing to duplicate the logic in the client, server, *and* the ServiceWorker, I would probably prefer to just use good ol' fashioned hashchange events, unless someone can convince me otherwise. (Yes, the URLs will look ugly; but hey, it'll be easy to implement.)

Either Page.js or Ampersand Router look like good candidates for this.

**Comment by jessetane** [comment]
First, thanks for the awesome app and write up, very educational stuff!

Some questions and thoughts on your routing points:

1 & 2) Although the history API is indeed weird and hard to work with, I think the more difficult challenge is altering the architecture to achieve animation idempotency. (Idempotence maybe isn't the exact concept, but I think it's close.) Imagine you add client side routing and a user clicks through a few Pokemon manually, before deciding to click the back button a few times in rapid succession. As currently structured, I think the app might break because the animation sequences require reaching completion (waiting for the transitionend event) to clean up and be prepared for their counterpart to play. As I understand it, these animations would need be designed in such a way as to allow for the possibility that they may _never_ complete, or be reversed halfway through. I don't have an exact example on hand but using lifecycle hooks may be a good place to start?
https://facebook.github.io/react/docs/component-specs.html#lifecycle-methods
https://github.com/jessetane/uri-router#lifecycle-hooks

3) As far as the server goes, what about serving static files if they exist, but falling back to index.html if they don't? The client can then render "pokemon not found" where appropriate. Here's [a version for node](https://github.com/substack/single-page/blob/master/example/server.js), but it's also pretty easy to get Nginx or Apache to do the same thing for use in production.

4) Why would the ServiceWorker need to know the URL? Isn't its job merely to get and cache all the assets required for the app to work offline? Is there a reason it can't do this happily in the background regardless of where the user is navigating? Maybe I'm missing something here.

**Comment by roryokane** [comment]
Yes, routing would be good. It’s not just a nice feature to add – it would solve a problem with the user interface.

When I used the site on my Android phone, and I was done viewing a single Pokémon’s details, I hit my phone’s Back button, because it was much closer to my thumb than the arrow in the top-left. But that took me back to the New Tab page, which was confusing and annoying. With routing, it would take me back to the list of all Pokémon like I expected it to.

**Comment by mhart** [comment]
If you want a super bare-bones approach to universal/isomorphic routing, check out the way I do it in [react-server-routing-example](https://github.com/mhart/react-server-routing-example) as a potential inspiration.

There are [basic regex routes and a resolving function](https://github.com/mhart/react-server-routing-example/blob/master/router.js), which are shared by both client and server (browserified). Then on the client, a [central handler for dealing with links and data fetching](https://github.com/mhart/react-server-routing-example/blob/master/App.js#L16-L44) and [on the server it's similarly straightforward](https://github.com/mhart/react-server-routing-example/blob/master/server.js#L17-L28).

**Comment by BHSPitMonkey** [comment]
A good way to do this is to put your routes behind a hash (e.g. pokedex.org/#bulbasaur) and simply make your UI buttons simply link accordingly using plain old anchor tags. Your app can then listen for window.location change events and update the UI accordingly.

**Comment by nolanlawson** [comment]
Thanks for the comments everyone! My thoughts:

> what about serving static files if they exist, but falling back to index.html if they don't?

Yes, that's exactly the trouble. During the build step, I would have to build up 649 HTML pages for each Pokémon, which is... time-consuming. Although yeah, it would be the best UX, because the detail view could just load instantly, without JS.

> Why would the ServiceWorker need to know the URL?

If I don't tell the service worker about e.g. `/monsters/1.html`, then when you try to navigate to it (or refresh), it will give you the sad offline dinosaur. So the ServiceWorker needs to know how to generate the `1.html` - `649.html` pages dynamically, i.e. it needs to do rendering.

I think based on all this discussion, I am definitely leaning towards using hash URLs (e.g. `pokedex.org/#bulbasaur` or `pokedex.org/#1`), since it makes the implementation much, much easier at the expense of ugly URLs and requiring javascript to animate the detail pages. The animations are also a tricky issue; we will need some way to short-circuit them in case the user taps back several times in rapid succession.

**Comment by jessetane** [comment]
I'm not sure I did a very good job of explaining what I meant about falling back to index.html, here is a demo: https://github.com/jessetane/pokedex.org/tree/routing
Hopefully it shows why the issue isn't necessarily about deciding on hash vs pathname?

**Comment by nolanlawson** [comment]
OK, I see what you're getting at there. The issue is that the `dev-server` uses Node as the backend, but in production I'm just using static S3 files. So if we wanted `pokedex.org/1` to work, there would need to be a literal HTML file called `1`.

Making this app a full Node app with an actual Node server is possible, but I really hadn't envisioned it, and I like the simplicity of just building up a static site. :/

**Comment by jessetane** [comment]
https://kkob.us/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/

**Comment by jessetane** [comment]
Agreed though, it's very nice to deploy only static files! I usually use nginx with the same technique :)

**Comment by jonkoops** [comment]
I would suggest using the name instead of the id in the URL (ì.e. `pokedex.org/bulbasaur`). It makes it clear to a user exactly what is being shared. The History API would look a lot cleaner than using the hash, with the article mentioned by @jessetane it should be possible to always serve index.html.

Henrik Joreteg has a pretty simple setup for routing in his [Feather App](https://github.com/HenrikJoreteg/feather-app) which takes the URL as a piece of state and uses conditionals to render part of a page. Don't know how exactly it would tie into Pokedex.org with all the animation going on between states, but it might be a good place to start. There would need to be some kind of way to keep the old rendered state in place when a route transition animation is performed (same idea as [Liquid Fire](https://ember-animation.github.io/liquid-fire/) for Ember).

**Comment by jessetane** [comment]
btw I realized you can do fallback routing with plain s3 (without having to use cloudfront) by just setting the error document to index.html, a caveat being that the status code will be set to 404...

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pokedex.org/pull/60
