### ISSUE TITLE
Why do you use a service worker and a web worker?

### ISSUE THREAD

**Issue by dumbmatter** [nolanlawson/pokedex.org#43]
Why not just do everything in the service worker? That would reduce the number of components you have to worry about, and multiple tabs could share the same worker. It might not matter too much here, but imagine if you had some user input that resulted in updating the database... it'd be nice if it was all using one cache in one service worker so multiple tabs would be consistent, right?

My apologies for abusing this issue tracker to get your advice :)

**Comment by nolanlawson** [comment]
1) not all browsers that support web workers support service workers (e.g. Edge)
2) even low-end Android devices have 4 cores. Main thread + WW + SW = 3 threads :)
3) performance characteristics of SW are slightly different from SW depending on the browser; e.g. in Chrome they are a separate process rather than a separate thread, so potentially higher communication costs (https://docs.google.com/document/d/1i3IA3TG00rpQ7MKlpNFYUF6EfLcV01_Cv3IYG_DjF7M/edit?usp=sharing)

Also... because I can. :)
